name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]  # Eller den branch du använder
  workflow_dispatch:    # Tillåter manuell körning

permissions:
  contents: write   # krävs för att deploy-action ska kunna pusha till gh-pages

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@v3
      
    # Om du behöver någon build-process, lägg till stegen här
    # Till exempel för minifiering, etc.
    
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages  # Branch där GitHub Pages kommer att publiceras
        folder: .         # Mappen som innehåller de statiska filerna
